import math

# print(math.e)
# print(math.pi)
# print(math.tau)
# print(math.inf)
# print(-math.inf)
# print(math.inf > 10e108)
# print(-math.inf < -10e108)
# print(math.nan)
# print(math.floor(2.9))
print(math.ceil(2.1))
# print(math.factorial(5))
# print(math.gcd(5,50))
# print(math.fabs(-10))
# print(math.exp(5))
# print(math.pow(5,2))
# print(math.log(2,3))
# print(math.log2(16))
# print(math.log10(10000))
# print(math.sqrt(4))
# print(math.sin(30)) #Trigonometric values should be in radian mode
# print(math.cos(50))
# print(math.tan(50))
# print(math.radians(30))
# print(math.degrees(0.5235987755982988))
# print(math.gamma(6))
# print(math.isinf(math.pi))
# print(math.isinf(math.e))
# print(math.isnan(math.pi))
# print(math.isnan(float('nan')))