from turtle import *
# import turtle

# wn = Screen()
# wn.bgcolor("Yellow")
# wn.title("Turtle")
# skk = Turtle()
# skk.forward(100)
# done()

wn = Screen()
wn.title("Square")
tt = Turtle()
# for i in range(4):
#     tt.forward(100)
#     tt.right(90)
# tt.right(75)
# tt.forward(100)
# tt.color("Red")
# tt.forward(100)
# tt.left(90)
# tt.forward(100)
# tt.left(135)
# tt.forward(150)
tt.speed(0)
# for i in range(100):
#     circle(5*i)
#     circle(-5*i)
#     left(i)
color("Red","Green")
begin_fill()
left(50)
forward(100)
circle(40,180)
left(260)
circle(40,180)
forward(100)
end_fill()
done()