/*Write a JavaScript program to pretend to look like a hacker. Write an async function
which will simply display the following output:

Initializing Hack Program...
Hacking Ashish's username...
Username found ashish17...
Connection to facebook...

Try to use HTML & styling if possible. */